### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by ibrahimlawal** [pauloladimeji/paystack-easy-digital-downloads#1]
Hi Paul,

Nice work here! What is the status of your plugin?

Thanks!

**Comment by pauloladimeji** [comment]
Hi Ibrahim,

The plugin has been tested and approved by the Paystack team. 

There is a live version running without any issues so far on https://gospelbox.com.ng ... You can a song to cart, and select "Paystack" as the processor on checkout. Let me know how it goes.

**Comment by ibrahimlawal** [comment]
Awesome. Thanks!

**Comment by ibrahimlawal** [comment]
Ah pls, installation instructions? Is it already listed in Wordpress plugins?

**Comment by pauloladimeji** [comment]
Download the repo as a ZIP and extract to your plugins folder. Activate on
your WordPress dashboard and you've got it.

You need to have Easy Digital Downloads installed and activated in your
wordpress website for the gateway to work. You can define your Paystack
keys from the "Payment Gateways" tab in the Easy Digital Downloads settings.

**Comment by pauloladimeji** [comment]
Not listed btw. I'll get around to that soon

**Comment by ibrahimlawal** [comment]
Hi Paul,

The Paystack API used for the current version of this plugin is outdated. There's new endpoints and specs. How soon can you update?

Thanks!

**Comment by pauloladimeji** [comment]
Oh. I've been busy so haven't noticed that.

I'll try to make time during the weekend. You can also create a PR in case
that'll be faster.

Thanks!

**Comment by ibrahimlawal** [comment]
PR sent!
